### ISSUE TITLE
can't encode character '\u02bb'

### ISSUE THREAD

**Issue by nschloe** [mcmtroffaes/latexcodec#84] opened 2020-06-18 11:47 UTC
Like #68.
```python
import codecs
import latexcodec

codecs.encode(u"\u02bb \u02bc", "ulatex")
```
See See nschloe/betterbib#153.

**Comment by mcmtroffaes** [comment] 2020-06-18 12:39
Thanks for reporting. I think I'll go for `` ` `` (alternatives might be \textturncomma or \textturncommaabove) and `` ' `` (alternatives might be \textcommaabove or \rasp) for these, but let me know if you have a better suggestion.

**Comment by nschloe** [comment] 2020-06-18 14:37
There's more here: https://github.com/nschloe/betterbib/pull/157/files.

**Comment by mcmtroffaes** [comment] 2020-06-22 13:58
This should now be fixed in develop. I've gone for the simple `` ' `` and `` ` `` variants. Can you confirm that the problem is fixed for you?

**Closed** 2020-06-23 09:58 UTC
